package com.example.qrakon.components.restaurants

import com.example.qrakon.R
import com.example.qrakon.components.restaurants.FoodItemDoubleF

object RestaurantData {

    val allFoodItems = listOf(
//      Top Picks pizza
        FoodItemDoubleF(
            id = 1,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_1,
                R.drawable.restaurant_image_pizzas_food_items_2
            ),
            title = "Chicken Pizza",
            price = "275",
            originalPrice = "375",
            restaurantName = "Burger Hub",
            rating = "4.3",
            deliveryTime = "20-25 mins",
            distance = "1.8 km",
            discount = "10% OFF",
            discountAmount = "₹25 OFF",
            address = "Food Street, City Center",
            calories = "450 kcal",
            protein = "22g",
            isHighProtein = true,
            category = "pizza",
            isWishlisted = false,
            description = "Juicy chicken burger with fresh lettuce, tomato and crispy fries",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "70",
            reorderedQuantity = "150+ orders",
            bestSeller = true,
            toppicks = true,
        ),
        FoodItemDoubleF(
            id = 2,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_2,
                R.drawable.restaurant_image_pizzas_food_items_3
            ),
            title = "Chilli Garlic Pizza",
            price = "363",
            originalPrice = "563",
            restaurantName = "Momo Express",
            rating = "4.5",
            deliveryTime = "25-30 mins",
            distance = "2.2 km",
            discount = "15% OFF",
            discountAmount = "₹40 OFF",
            address = "Downtown Food Plaza",
            calories = "380 kcal",
            protein = "14g",
            isHighProtein = false,
            category = "pizza",
            isWishlisted = true,
            description = "Spicy chilli garlic momos tossed with flavorful sauces and herbs",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "65",
            reorderedQuantity = "200+ orders",
            bestSeller = false,
            toppicks = true,
        ),
        FoodItemDoubleF(
            id = 3,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_3,
                R.drawable.restaurant_image_pizzas_food_items_4
            ),
            title = "Ultimate Cheese Pizza",
            price = "399",
            originalPrice = "499",
            restaurantName = "Pizza Heaven",
            rating = "4.3",
            deliveryTime = "25-30 mins",
            distance = "2.5 km",
            discount = "",
            discountAmount = "",
            address = "Food Court, Mall Road",
            calories = "780 kcal",
            protein = "24g",
            isHighProtein = false,
            category = "pizza",
            isWishlisted = false,
            description = "Classic margherita with extra cheese and basil",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "",
            reorderedQuantity = "",
            bestSeller = false,
            toppicks = true
        ),
        FoodItemDoubleF(
            id = 4,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_4,
                R.drawable.restaurant_image_pizzas_food_items_5
            ),
            title = "Corn Pizza",
            price = "139",
            originalPrice = "239",
            restaurantName = "Pizza Corner",
            rating = "3.8",
            deliveryTime = "20-25 mins",
            distance = "1.5 km",
            discount = "",
            discountAmount = "",
            address = "Street Food Market",
            calories = "620 kcal",
            protein = "16g",
            isHighProtein = false,
            category = "pizza",
            isWishlisted = false,
            description = "Sweet corn pizza with creamy sauce",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "Highly reordered",
            reorderedQuantity = "",
            bestSeller = true,
            toppicks = true,
        ),
        FoodItemDoubleF(
            id = 5,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_5,
                R.drawable.restaurant_image_pizzas_food_items_6
            ),
            title = "Ultimate Flotzz Pizza",
            price = "399",
            originalPrice = "499",
            restaurantName = "Flotzz Pizza",
            rating = "4.2",
            deliveryTime = "30-35 mins",
            distance = "3.0 km",
            discount = "",
            discountAmount = "",
            address = "Food Plaza, Sector 5",
            calories = "850 kcal",
            protein = "32g",
            isHighProtein = true,
            category = "pizza",
            isWishlisted = false,
            description = "Loaded with cheese and toppings",
            quantity = "1",
            infoIcon = R.drawable.ic_non_veg_rest,
            highlyReordered = "",
            reorderedQuantity = "500+ orders",
            bestSeller = true,
            toppicks = true,
        ),
        FoodItemDoubleF(
            id = 6,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_6,
                R.drawable.restaurant_image_pizzas_food_items_1
            ),
            title = "Tandoori Chicken Pizza",
            price = "399",
            originalPrice = "499",
            restaurantName = "Flotzz Pizza",
            rating = "4.5",
            deliveryTime = "30-35 mins",
            distance = "3.0 km",
            discount = "",
            discountAmount = "",
            address = "Food Plaza, Sector 5",
            calories = "890 kcal",
            protein = "38g",
            isHighProtein = true,
            category = "pizza",
            isWishlisted = true,
            description = "Tandoori chicken with spicy sauce",
            quantity = "1",
            infoIcon = R.drawable.ic_non_veg_rest,
            highlyReordered = "",
            reorderedQuantity = "500+ orders",
            bestSeller = false,
            toppicks = true,
        ),

        //      Free Delivery pizza
        FoodItemDoubleF(
            id = 7,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_1,
                R.drawable.restaurant_image_pizzas_food_items_2
            ),
            title = "Chicken Pizza",
            price = "275",
            originalPrice = "375",
            restaurantName = "Burger Hub",
            rating = "4.3",
            deliveryTime = "20-25 mins",
            distance = "1.8 km",
            discount = "10% OFF",
            discountAmount = "₹25 OFF",
            address = "Food Street, City Center",
            calories = "450 kcal",
            protein = "22g",
            isHighProtein = true,
            category = "pizza",
            isWishlisted = false,
            description = "Juicy chicken burger with fresh lettuce, tomato and crispy fries",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "70",
            reorderedQuantity = "150+ orders",
            bestSeller = true,
            freedelivery = true,
        ),
        FoodItemDoubleF(
            id = 8,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_2,
                R.drawable.restaurant_image_pizzas_food_items_3
            ),
            title = "Chilli Garlic Pizza",
            price = "363",
            originalPrice = "563",
            restaurantName = "Momo Express",
            rating = "4.5",
            deliveryTime = "25-30 mins",
            distance = "2.2 km",
            discount = "15% OFF",
            discountAmount = "₹40 OFF",
            address = "Downtown Food Plaza",
            calories = "380 kcal",
            protein = "14g",
            isHighProtein = false,
            category = "pizza",
            isWishlisted = true,
            description = "Spicy chilli garlic momos tossed with flavorful sauces and herbs",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "65",
            reorderedQuantity = "200+ orders",
            bestSeller = false,
            freedelivery = true,
        ),
        FoodItemDoubleF(
            id = 9,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_3,
                R.drawable.restaurant_image_pizzas_food_items_4
            ),
            title = "Ultimate Cheese Pizza",
            price = "399",
            originalPrice = "499",
            restaurantName = "Pizza Heaven",
            rating = "4.3",
            deliveryTime = "25-30 mins",
            distance = "2.5 km",
            discount = "",
            discountAmount = "",
            address = "Food Court, Mall Road",
            calories = "780 kcal",
            protein = "24g",
            isHighProtein = false,
            category = "pizza",
            isWishlisted = false,
            description = "Classic margherita with extra cheese and basil",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "",
            reorderedQuantity = "",
            bestSeller = false,
            freedelivery = true
        ),
        FoodItemDoubleF(
            id = 10,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_4,
                R.drawable.restaurant_image_pizzas_food_items_5
            ),
            title = "Corn Pizza",
            price = "139",
            originalPrice = "239",
            restaurantName = "Pizza Corner",
            rating = "3.8",
            deliveryTime = "20-25 mins",
            distance = "1.5 km",
            discount = "",
            discountAmount = "",
            address = "Street Food Market",
            calories = "620 kcal",
            protein = "16g",
            isHighProtein = false,
            category = "pizza",
            isWishlisted = false,
            description = "Sweet corn pizza with creamy sauce",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "Highly reordered",
            reorderedQuantity = "",
            bestSeller = true,
            freedelivery = true,
        ),
        FoodItemDoubleF(
            id = 11,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_5,
                R.drawable.restaurant_image_pizzas_food_items_6
            ),
            title = "Ultimate Flotzz Pizza",
            price = "399",
            originalPrice = "499",
            restaurantName = "Flotzz Pizza",
            rating = "4.2",
            deliveryTime = "30-35 mins",
            distance = "3.0 km",
            discount = "",
            discountAmount = "",
            address = "Food Plaza, Sector 5",
            calories = "850 kcal",
            protein = "32g",
            isHighProtein = true,
            category = "pizza",
            isWishlisted = false,
            description = "Loaded with cheese and toppings",
            quantity = "1",
            infoIcon = R.drawable.ic_non_veg_rest,
            highlyReordered = "",
            reorderedQuantity = "500+ orders",
            bestSeller = true,
            freedelivery = true,
        ),
        FoodItemDoubleF(
            id = 12,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_6,
                R.drawable.restaurant_image_pizzas_food_items_1
            ),
            title = "Tandoori Chicken Pizza",
            price = "399",
            originalPrice = "499",
            restaurantName = "Flotzz Pizza",
            rating = "4.5",
            deliveryTime = "30-35 mins",
            distance = "3.0 km",
            discount = "",
            discountAmount = "",
            address = "Food Plaza, Sector 5",
            calories = "890 kcal",
            protein = "38g",
            isHighProtein = true,
            category = "pizza",
            isWishlisted = true,
            description = "Tandoori chicken with spicy sauce",
            quantity = "1",
            infoIcon = R.drawable.ic_non_veg_rest,
            highlyReordered = "",
            reorderedQuantity = "500+ orders",
            bestSeller = false,
            freedelivery = true,
        ),

        //      Recommended pizza
        FoodItemDoubleF(
            id = 13,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_1,
                R.drawable.restaurant_image_pizzas_food_items_2
            ),
            title = "Chicken Pizza",
            price = "275",
            originalPrice = "375",
            restaurantName = "Burger Hub",
            rating = "4.3",
            deliveryTime = "20-25 mins",
            distance = "1.8 km",
            discount = "10% OFF",
            discountAmount = "₹25 OFF",
            address = "Food Street, City Center",
            calories = "450 kcal",
            protein = "22g",
            isHighProtein = true,
            category = "pizza",
            isWishlisted = false,
            description = "Juicy chicken burger with fresh lettuce, tomato and crispy fries",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "70",
            reorderedQuantity = "150+ orders",
            bestSeller = true,
            recommended = true,
        ),
        FoodItemDoubleF(
            id = 14,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_2,
                R.drawable.restaurant_image_pizzas_food_items_3
            ),
            title = "Chilli Garlic Pizza",
            price = "363",
            originalPrice = "563",
            restaurantName = "Momo Express",
            rating = "4.5",
            deliveryTime = "25-30 mins",
            distance = "2.2 km",
            discount = "15% OFF",
            discountAmount = "₹40 OFF",
            address = "Downtown Food Plaza",
            calories = "380 kcal",
            protein = "14g",
            isHighProtein = false,
            category = "pizza",
            isWishlisted = true,
            description = "Spicy chilli garlic momos tossed with flavorful sauces and herbs",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "65",
            reorderedQuantity = "200+ orders",
            bestSeller = false,
            recommended = true,
        ),
        FoodItemDoubleF(
            id = 15,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_3,
                R.drawable.restaurant_image_pizzas_food_items_4
            ),
            title = "Ultimate Cheese Pizza",
            price = "399",
            originalPrice = "499",
            restaurantName = "Pizza Heaven",
            rating = "4.3",
            deliveryTime = "25-30 mins",
            distance = "2.5 km",
            discount = "",
            discountAmount = "",
            address = "Food Court, Mall Road",
            calories = "780 kcal",
            protein = "24g",
            isHighProtein = false,
            category = "pizza",
            isWishlisted = false,
            description = "Classic margherita with extra cheese and basil",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "",
            reorderedQuantity = "",
            bestSeller = false,
            recommended = true
        ),
        FoodItemDoubleF(
            id = 16,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_4,
                R.drawable.restaurant_image_pizzas_food_items_5
            ),
            title = "Corn Pizza",
            price = "139",
            originalPrice = "239",
            restaurantName = "Pizza Corner",
            rating = "3.8",
            deliveryTime = "20-25 mins",
            distance = "1.5 km",
            discount = "",
            discountAmount = "",
            address = "Street Food Market",
            calories = "620 kcal",
            protein = "16g",
            isHighProtein = false,
            category = "pizza",
            isWishlisted = false,
            description = "Sweet corn pizza with creamy sauce",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "Highly reordered",
            reorderedQuantity = "",
            bestSeller = true,
            recommended = true,
        ),
        FoodItemDoubleF(
            id = 17,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_5,
                R.drawable.restaurant_image_pizzas_food_items_6
            ),
            title = "Ultimate Flotzz Pizza",
            price = "399",
            originalPrice = "499",
            restaurantName = "Flotzz Pizza",
            rating = "4.2",
            deliveryTime = "30-35 mins",
            distance = "3.0 km",
            discount = "",
            discountAmount = "",
            address = "Food Plaza, Sector 5",
            calories = "850 kcal",
            protein = "32g",
            isHighProtein = true,
            category = "pizza",
            isWishlisted = false,
            description = "Loaded with cheese and toppings",
            quantity = "1",
            infoIcon = R.drawable.ic_non_veg_rest,
            highlyReordered = "",
            reorderedQuantity = "500+ orders",
            bestSeller = true,
            recommended = true,
        ),
        FoodItemDoubleF(
            id = 18,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_6,
                R.drawable.restaurant_image_pizzas_food_items_1
            ),
            title = "Tandoori Chicken Pizza",
            price = "399",
            originalPrice = "499",
            restaurantName = "Flotzz Pizza",
            rating = "4.5",
            deliveryTime = "30-35 mins",
            distance = "3.0 km",
            discount = "",
            discountAmount = "",
            address = "Food Plaza, Sector 5",
            calories = "890 kcal",
            protein = "38g",
            isHighProtein = true,
            category = "pizza",
            isWishlisted = true,
            description = "Tandoori chicken with spicy sauce",
            quantity = "1",
            infoIcon = R.drawable.ic_non_veg_rest,
            highlyReordered = "",
            reorderedQuantity = "500+ orders",
            bestSeller = false,
            recommended = true,
        ),

        //      Combo pizza
        FoodItemDoubleF(
            id = 19,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_1,
                R.drawable.restaurant_image_pizzas_food_items_2
            ),
            title = "Chicken Pizza + Chilli Garlic Pizza",
            price = "275",
            originalPrice = "375",
            restaurantName = "Burger Hub",
            rating = "4.3",
            deliveryTime = "20-25 mins",
            distance = "1.8 km",
            discount = "10% OFF",
            discountAmount = "₹25 OFF",
            address = "Food Street, City Center",
            calories = "450 kcal",
            protein = "22g",
            isHighProtein = true,
            category = "pizza",
            isWishlisted = false,
            description = "Juicy chicken burger with fresh lettuce, tomato and crispy fries",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "70",
            reorderedQuantity = "150+ orders",
            bestSeller = true,
            combo = true,
        ),
        FoodItemDoubleF(
            id = 20,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_2,
                R.drawable.restaurant_image_pizzas_food_items_3
            ),
            title = "Chilli Garlic Pizza + Ultimate Cheese Pizza",
            price = "363",
            originalPrice = "563",
            restaurantName = "Momo Express",
            rating = "4.5",
            deliveryTime = "25-30 mins",
            distance = "2.2 km",
            discount = "15% OFF",
            discountAmount = "₹40 OFF",
            address = "Downtown Food Plaza",
            calories = "380 kcal",
            protein = "14g",
            isHighProtein = false,
            category = "pizza",
            isWishlisted = true,
            description = "Spicy chilli garlic momos tossed with flavorful sauces and herbs",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "65",
            reorderedQuantity = "200+ orders",
            bestSeller = false,
            combo = true,
        ),
        FoodItemDoubleF(
            id = 21,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_3,
                R.drawable.restaurant_image_pizzas_food_items_4
            ),
            title = "Ultimate Cheese Pizza + Corn Pizza",
            price = "399",
            originalPrice = "499",
            restaurantName = "Pizza Heaven",
            rating = "4.3",
            deliveryTime = "25-30 mins",
            distance = "2.5 km",
            discount = "",
            discountAmount = "",
            address = "Food Court, Mall Road",
            calories = "780 kcal",
            protein = "24g",
            isHighProtein = false,
            category = "pizza",
            isWishlisted = false,
            description = "Classic margherita with extra cheese and basil",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "",
            reorderedQuantity = "",
            bestSeller = false,
            combo = true
        ),
        FoodItemDoubleF(
            id = 22,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_4,
                R.drawable.restaurant_image_pizzas_food_items_5
            ),
            title = "Corn Pizza + Ultimate Flotzz Pizza",
            price = "139",
            originalPrice = "239",
            restaurantName = "Pizza Corner",
            rating = "3.8",
            deliveryTime = "20-25 mins",
            distance = "1.5 km",
            discount = "",
            discountAmount = "",
            address = "Street Food Market",
            calories = "620 kcal",
            protein = "16g",
            isHighProtein = false,
            category = "pizza",
            isWishlisted = false,
            description = "Sweet corn pizza with creamy sauce",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "Highly reordered",
            reorderedQuantity = "",
            bestSeller = true,
            combo = true,
        ),
        FoodItemDoubleF(
            id = 23,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_5,
                R.drawable.restaurant_image_pizzas_food_items_6
            ),
            title = "Ultimate Flotzz Pizza + Tandoori Chicken Pizza",
            price = "399",
            originalPrice = "499",
            restaurantName = "Flotzz Pizza",
            rating = "4.2",
            deliveryTime = "30-35 mins",
            distance = "3.0 km",
            discount = "",
            discountAmount = "",
            address = "Food Plaza, Sector 5",
            calories = "850 kcal",
            protein = "32g",
            isHighProtein = true,
            category = "pizza",
            isWishlisted = false,
            description = "Loaded with cheese and toppings",
            quantity = "1",
            infoIcon = R.drawable.ic_non_veg_rest,
            highlyReordered = "",
            reorderedQuantity = "500+ orders",
            bestSeller = true,
            combo = true,
        ),
        FoodItemDoubleF(
            id = 24,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_6,
                R.drawable.restaurant_image_pizzas_food_items_1
            ),
            title = "Tandoori Chicken Pizza + Chicken Pizza",
            price = "399",
            originalPrice = "499",
            restaurantName = "Flotzz Pizza",
            rating = "4.5",
            deliveryTime = "30-35 mins",
            distance = "3.0 km",
            discount = "",
            discountAmount = "",
            address = "Food Plaza, Sector 5",
            calories = "890 kcal",
            protein = "38g",
            isHighProtein = true,
            category = "pizza",
            isWishlisted = true,
            description = "Tandoori chicken with spicy sauce",
            quantity = "1",
            infoIcon = R.drawable.ic_non_veg_rest,
            highlyReordered = "",
            reorderedQuantity = "500+ orders",
            bestSeller = false,
            combo = true,
        ),

        //      More Details Button pizza
        FoodItemDoubleF(
            id = 25,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_1,
                R.drawable.restaurant_image_pizzas_food_items_2
            ),
            title = "Chicken Pizza + Chilli Garlic Pizza",
            price = "275",
            originalPrice = "375",
            restaurantName = "Burger Hub",
            rating = "4.3",
            deliveryTime = "20-25 mins",
            distance = "1.8 km",
            discount = "10% OFF",
            discountAmount = "₹25 OFF",
            address = "Food Street, City Center",
            calories = "450 kcal",
            protein = "22g",
            isHighProtein = true,
            category = "pizza",
            isWishlisted = false,
            description = "Juicy chicken burger with fresh lettuce, tomato and crispy fries",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "70",
            reorderedQuantity = "150+ orders",
            bestSeller = true,
            moredetailsbutton = true,
        ),
        FoodItemDoubleF(
            id = 26,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_2,
                R.drawable.restaurant_image_pizzas_food_items_3
            ),
            title = "Chilli Garlic Pizza + Ultimate Cheese Pizza",
            price = "363",
            originalPrice = "563",
            restaurantName = "Momo Express",
            rating = "4.5",
            deliveryTime = "25-30 mins",
            distance = "2.2 km",
            discount = "15% OFF",
            discountAmount = "₹40 OFF",
            address = "Downtown Food Plaza",
            calories = "380 kcal",
            protein = "14g",
            isHighProtein = false,
            category = "pizza",
            isWishlisted = true,
            description = "Spicy chilli garlic momos tossed with flavorful sauces and herbs",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "65",
            reorderedQuantity = "200+ orders",
            bestSeller = false,
            moredetailsbutton = true,
        ),
        FoodItemDoubleF(
            id = 27,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_3,
                R.drawable.restaurant_image_pizzas_food_items_4
            ),
            title = "Ultimate Cheese Pizza + Corn Pizza",
            price = "399",
            originalPrice = "499",
            restaurantName = "Pizza Heaven",
            rating = "4.3",
            deliveryTime = "25-30 mins",
            distance = "2.5 km",
            discount = "",
            discountAmount = "",
            address = "Food Court, Mall Road",
            calories = "780 kcal",
            protein = "24g",
            isHighProtein = false,
            category = "pizza",
            isWishlisted = false,
            description = "Classic margherita with extra cheese and basil",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "",
            reorderedQuantity = "",
            bestSeller = false,
            moredetailsbutton = true
        ),
        FoodItemDoubleF(
            id = 28,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_4,
                R.drawable.restaurant_image_pizzas_food_items_5
            ),
            title = "Corn Pizza + Ultimate Flotzz Pizza",
            price = "139",
            originalPrice = "239",
            restaurantName = "Pizza Corner",
            rating = "3.8",
            deliveryTime = "20-25 mins",
            distance = "1.5 km",
            discount = "",
            discountAmount = "",
            address = "Street Food Market",
            calories = "620 kcal",
            protein = "16g",
            isHighProtein = false,
            category = "pizza",
            isWishlisted = false,
            description = "Sweet corn pizza with creamy sauce",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "Highly reordered",
            reorderedQuantity = "",
            bestSeller = true,
            moredetailsbutton = true,
        ),
        FoodItemDoubleF(
            id = 29,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_5,
                R.drawable.restaurant_image_pizzas_food_items_6
            ),
            title = "Ultimate Flotzz Pizza + Tandoori Chicken Pizza",
            price = "399",
            originalPrice = "499",
            restaurantName = "Flotzz Pizza",
            rating = "4.2",
            deliveryTime = "30-35 mins",
            distance = "3.0 km",
            discount = "",
            discountAmount = "",
            address = "Food Plaza, Sector 5",
            calories = "850 kcal",
            protein = "32g",
            isHighProtein = true,
            category = "pizza",
            isWishlisted = false,
            description = "Loaded with cheese and toppings",
            quantity = "1",
            infoIcon = R.drawable.ic_non_veg_rest,
            highlyReordered = "",
            reorderedQuantity = "500+ orders",
            bestSeller = true,
            moredetailsbutton = true,
        ),
        FoodItemDoubleF(
            id = 30,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_6,
                R.drawable.restaurant_image_pizzas_food_items_1
            ),
            title = "Tandoori Chicken Pizza + Chicken Pizza",
            price = "399",
            originalPrice = "499",
            restaurantName = "Flotzz Pizza",
            rating = "4.5",
            deliveryTime = "30-35 mins",
            distance = "3.0 km",
            discount = "",
            discountAmount = "",
            address = "Food Plaza, Sector 5",
            calories = "890 kcal",
            protein = "38g",
            isHighProtein = true,
            category = "pizza",
            isWishlisted = true,
            description = "Tandoori chicken with spicy sauce",
            quantity = "1",
            infoIcon = R.drawable.ic_non_veg_rest,
            highlyReordered = "",
            reorderedQuantity = "500+ orders",
            bestSeller = false,
            moredetailsbutton = true,
        ),

        //      Salad pizza
        FoodItemDoubleF(
            id = 31,
            imageRes = listOf(R.drawable.salad_veg_shammi),
            title = "Veg Shammi Salad",
            price = "289",
            originalPrice = "389",
            restaurantName = "FreshBowl",
            rating = "4.4",
            deliveryTime = "",
            distance = "",
            discount = "",
            discountAmount = "",
            address = "",
            calories = "361 kcal",
            protein = "13g",
            isHighProtein = true,
            category = "pizza",
            isWishlisted = false,
            description = "Fresh cottage cheese marinated with spices, grilled to perfection on a bed of mixed greens",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "41",
            reorderedQuantity = "41 ratings",
            bestSeller = false,
            salad = true,
        ),
        FoodItemDoubleF(
            id = 32,
            imageRes = listOf(R.drawable.salad_smoked_chicken),
            title = "Smoked Chicken Strips Salad",
            price = "319",
            originalPrice = "419",
            restaurantName = "FreshBowl",
            rating = "4.2",
            deliveryTime = "",
            distance = "",
            discount = "",
            discountAmount = "",
            address = "",
            calories = "337 kcal",
            protein = "22g",
            isHighProtein = true,
            category = "pizza",
            isWishlisted = false,
            description = "Tender smoked chicken strips with mixed greens, cherry tomatoes, and honey mustard dressing",
            quantity = "1",
            infoIcon = R.drawable.ic_non_veg_rest,
            highlyReordered = "0",
            reorderedQuantity = "",
            bestSeller = false,
            salad = true,
        ),
        FoodItemDoubleF(
            id = 33,
            imageRes = listOf(R.drawable.salad_paneer_tikka),
            title = "Paneer Tikka Salad",
            price = "289",
            originalPrice = "389",
            restaurantName = "FreshBowl",
            rating = "4.6",
            deliveryTime = "",
            distance = "",
            discount = "",
            discountAmount = "",
            address = "",
            calories = "380 kcal",
            protein = "18g",
            isHighProtein = true,
            category = "pizza",
            isWishlisted = false,
            description = "Chargrilled paneer tikka on a bed of fresh veggies with mint chutney dressing",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "0",
            reorderedQuantity = "",
            bestSeller = true,
            salad = true,
        ),
        FoodItemDoubleF(
            id = 34,
            imageRes = listOf(R.drawable.salad_veggie_delite),
            title = "Veggie Delite Salad",
            price = "289",
            originalPrice = "389",
            restaurantName = "FreshBowl",
            rating = "4.0",
            deliveryTime = "",
            distance = "",
            discount = "",
            discountAmount = "",
            address = "",
            calories = "210 kcal",
            protein = "6g",
            isHighProtein = false,
            category = "pizza",
            isWishlisted = false,
            description = "Fresh garden veggies including lettuce, cucumbers, bell peppers with light vinaigrette",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "0",
            reorderedQuantity = "",
            bestSeller = false,
            salad = true,
        ),
        FoodItemDoubleF(
            id = 35,
            imageRes = listOf(R.drawable.salad_corn_peas),
            title = "Corn & Peas Salad",
            price = "289",
            originalPrice = "389",
            restaurantName = "FreshBowl",
            rating = "4.8",
            deliveryTime = "",
            distance = "",
            discount = "",
            discountAmount = "",
            address = "",
            calories = "188 kcal",
            protein = "5g",
            isHighProtein = false,
            category = "pizza",
            isWishlisted = false,
            description = "Sweet corn and green peas mixed with creamy yogurt dressing",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "28",
            reorderedQuantity = "28 ratings",
            bestSeller = false,
            salad = true,
        ),
        FoodItemDoubleF(
            id = 36,
            imageRes = listOf(R.drawable.salad_bmt),
            title = "B.M.T. Salad",
            price = "349",
            originalPrice = "449",
            restaurantName = "FreshBowl",
            rating = "5.0",
            deliveryTime = "",
            distance = "",
            discount = "",
            discountAmount = "",
            address = "",
            calories = "372 kcal",
            protein = "27g",
            isHighProtein = true,
            category = "pizza",
            isWishlisted = false,
            description = "Hearty salad with multiple meats, fresh veggies, and signature sauce",
            quantity = "1",
            infoIcon = R.drawable.ic_non_veg_rest,
            highlyReordered = "7",
            reorderedQuantity = "7 ratings",
            bestSeller = false,
            salad = true,
        ),


        // Top Picks Burger category items (id 37 to 42)
        FoodItemDoubleF(
            id = 37,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_7,
                R.drawable.restaurant_image_pizzas_food_items_8
            ),
            title = "Crispy Veg Burger",
            price = "72",
            originalPrice = "120",
            restaurantName = "Burger King",
            rating = "5.0",
            deliveryTime = "15-20 mins",
            distance = "1.2 km",
            discount = "40% OFF",
            discountAmount = "₹48 OFF",
            address = "Food Street, City Center",
            calories = "450 kcal",
            protein = "15g",
            isHighProtein = false,
            category = "burger",
            isWishlisted = false,
            description = "Crispy veg patty with fresh lettuce and special sauce",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "95",
            reorderedQuantity = "500+ orders",
            bestSeller = true,
            toppicks = true,
            ),
        FoodItemDoubleF(
            id = 38,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_8,
                R.drawable.restaurant_image_pizzas_food_items_9
            ),
            title = "Crispy Chicken Burger",
            price = "79",
            originalPrice = "140",
            restaurantName = "Burger King",
            rating = "4.2",
            deliveryTime = "15-20 mins",
            distance = "1.3 km",
            discount = "35% OFF",
            discountAmount = "₹61 OFF",
            address = "Food Street, City Center",
            calories = "520 kcal",
            protein = "22g",
            isHighProtein = true,
            category = "burger",
            isWishlisted = false,
            description = "Crispy chicken patty with mayo and fresh veggies",
            quantity = "1",
            infoIcon = R.drawable.ic_non_veg_rest,
            highlyReordered = "85",
            reorderedQuantity = "569+ orders",
            bestSeller = true,
            toppicks = true,
        ),
        FoodItemDoubleF(
            id = 39,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_9,
                R.drawable.restaurant_image_pizzas_food_items_10
            ),
            title = "Mexican Aloo Tikki Burger",
            price = "99",
            originalPrice = "160",
            restaurantName = "Burger King",
            rating = "4.3",
            deliveryTime = "18-22 mins",
            distance = "1.4 km",
            discount = "38% OFF",
            discountAmount = "₹61 OFF",
            address = "Food Plaza, Sector 5",
            calories = "480 kcal",
            protein = "12g",
            isHighProtein = false,
            category = "burger",
            isWishlisted = false,
            description = "Spicy aloo tikki with Mexican salsa and cheese",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "88",
            reorderedQuantity = "454+ orders",
            bestSeller = true,
            toppicks = true,
        ),
        FoodItemDoubleF(
            id = 40,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_10,
                R.drawable.restaurant_image_pizzas_food_items_11
            ),
            title = "Veg American Cheese Supreme Burger",
            price = "129",
            originalPrice = "200",
            restaurantName = "Burger King",
            rating = "4.5",
            deliveryTime = "20-25 mins",
            distance = "1.5 km",
            discount = "35% OFF",
            discountAmount = "₹71 OFF",
            address = "Food Plaza, Sector 5",
            calories = "560 kcal",
            protein = "18g",
            isHighProtein = false,
            category = "burger",
            isWishlisted = false,
            description = "Double cheese, crispy veg patty, and special sauce",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "92",
            reorderedQuantity = "525+ orders",
            bestSeller = true,
            toppicks = true,
        ),
        FoodItemDoubleF(
            id = 41,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_11,
                R.drawable.restaurant_image_pizzas_food_items_12
            ),
            title = "Royal Veg Burger",
            price = "198",
            originalPrice = "280",
            restaurantName = "Burger King",
            rating = "4.5",
            deliveryTime = "20-25 mins",
            distance = "1.5 km",
            discount = "29% OFF",
            discountAmount = "₹82 OFF",
            address = "Food Plaza, Sector 5",
            calories = "620 kcal",
            protein = "20g",
            isHighProtein = false,
            category = "burger",
            isWishlisted = false,
            description = "Premium veg burger with exotic veggies and royal sauce",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "90",
            reorderedQuantity = "400+ orders",
            bestSeller = true,
            toppicks = true,
        ),
        FoodItemDoubleF(
            id = 42,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_12,
                R.drawable.restaurant_image_pizzas_food_items_7
            ),
            title = "Paneer Tikka Burger",
            price = "149",
            originalPrice = "220",
            restaurantName = "Burger King",
            rating = "4.6",
            deliveryTime = "18-22 mins",
            distance = "1.3 km",
            discount = "32% OFF",
            discountAmount = "₹71 OFF",
            address = "Food Street, City Center",
            calories = "510 kcal",
            protein = "19g",
            isHighProtein = true,
            category = "burger",
            isWishlisted = false,
            description = "Grilled paneer tikka burger with mint chutney",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "93",
            reorderedQuantity = "350+ orders",
            bestSeller = true,
            toppicks = true,
        ),

        // Free Delivery Burger category items (id 43 to 48)
        FoodItemDoubleF(
            id = 43,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_7,
                R.drawable.restaurant_image_pizzas_food_items_8
            ),
            title = "Crispy Veg Burger",
            price = "72",
            originalPrice = "120",
            restaurantName = "Burger King",
            rating = "5.0",
            deliveryTime = "15-20 mins",
            distance = "1.2 km",
            discount = "40% OFF",
            discountAmount = "₹48 OFF",
            address = "Food Street, City Center",
            calories = "450 kcal",
            protein = "15g",
            isHighProtein = false,
            category = "burger",
            isWishlisted = false,
            description = "Crispy veg patty with fresh lettuce and special sauce",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "95",
            reorderedQuantity = "500+ orders",
            bestSeller = true,
            freedelivery = true,
        ),
        FoodItemDoubleF(
            id = 44,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_8,
                R.drawable.restaurant_image_pizzas_food_items_9
            ),
            title = "Crispy Chicken Burger",
            price = "79",
            originalPrice = "140",
            restaurantName = "Burger King",
            rating = "4.2",
            deliveryTime = "15-20 mins",
            distance = "1.3 km",
            discount = "35% OFF",
            discountAmount = "₹61 OFF",
            address = "Food Street, City Center",
            calories = "520 kcal",
            protein = "22g",
            isHighProtein = true,
            category = "burger",
            isWishlisted = false,
            description = "Crispy chicken patty with mayo and fresh veggies",
            quantity = "1",
            infoIcon = R.drawable.ic_non_veg_rest,
            highlyReordered = "85",
            reorderedQuantity = "569+ orders",
            bestSeller = true,
            freedelivery = true,
        ),
        FoodItemDoubleF(
            id = 45,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_9,
                R.drawable.restaurant_image_pizzas_food_items_10
            ),
            title = "Mexican Aloo Tikki Burger",
            price = "99",
            originalPrice = "160",
            restaurantName = "Burger King",
            rating = "4.3",
            deliveryTime = "18-22 mins",
            distance = "1.4 km",
            discount = "38% OFF",
            discountAmount = "₹61 OFF",
            address = "Food Plaza, Sector 5",
            calories = "480 kcal",
            protein = "12g",
            isHighProtein = false,
            category = "burger",
            isWishlisted = false,
            description = "Spicy aloo tikki with Mexican salsa and cheese",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "88",
            reorderedQuantity = "454+ orders",
            bestSeller = true,
            freedelivery = true,
        ),
        FoodItemDoubleF(
            id = 46,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_10,
                R.drawable.restaurant_image_pizzas_food_items_11
            ),
            title = "Veg American Cheese Supreme Burger",
            price = "129",
            originalPrice = "200",
            restaurantName = "Burger King",
            rating = "4.5",
            deliveryTime = "20-25 mins",
            distance = "1.5 km",
            discount = "35% OFF",
            discountAmount = "₹71 OFF",
            address = "Food Plaza, Sector 5",
            calories = "560 kcal",
            protein = "18g",
            isHighProtein = false,
            category = "burger",
            isWishlisted = false,
            description = "Double cheese, crispy veg patty, and special sauce",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "92",
            reorderedQuantity = "525+ orders",
            bestSeller = true,
            freedelivery = true,
        ),
        FoodItemDoubleF(
            id = 47,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_11,
                R.drawable.restaurant_image_pizzas_food_items_12
            ),
            title = "Royal Veg Burger",
            price = "198",
            originalPrice = "280",
            restaurantName = "Burger King",
            rating = "4.5",
            deliveryTime = "20-25 mins",
            distance = "1.5 km",
            discount = "29% OFF",
            discountAmount = "₹82 OFF",
            address = "Food Plaza, Sector 5",
            calories = "620 kcal",
            protein = "20g",
            isHighProtein = false,
            category = "burger",
            isWishlisted = false,
            description = "Premium veg burger with exotic veggies and royal sauce",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "90",
            reorderedQuantity = "400+ orders",
            bestSeller = true,
            freedelivery = true,
        ),
        FoodItemDoubleF(
            id = 48,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_12,
                R.drawable.restaurant_image_pizzas_food_items_7
            ),
            title = "Paneer Tikka Burger",
            price = "149",
            originalPrice = "220",
            restaurantName = "Burger King",
            rating = "4.6",
            deliveryTime = "18-22 mins",
            distance = "1.3 km",
            discount = "32% OFF",
            discountAmount = "₹71 OFF",
            address = "Food Street, City Center",
            calories = "510 kcal",
            protein = "19g",
            isHighProtein = true,
            category = "burger",
            isWishlisted = false,
            description = "Grilled paneer tikka burger with mint chutney",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "93",
            reorderedQuantity = "350+ orders",
            bestSeller = true,
            freedelivery = true,
        ),

        // Recommended Burger category items (id 49 to 54)
        FoodItemDoubleF(
            id = 49,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_7,
                R.drawable.restaurant_image_pizzas_food_items_8
            ),
            title = "Crispy Veg Burger",
            price = "72",
            originalPrice = "120",
            restaurantName = "Burger King",
            rating = "5.0",
            deliveryTime = "15-20 mins",
            distance = "1.2 km",
            discount = "40% OFF",
            discountAmount = "₹48 OFF",
            address = "Food Street, City Center",
            calories = "450 kcal",
            protein = "15g",
            isHighProtein = false,
            category = "burger",
            isWishlisted = false,
            description = "Crispy veg patty with fresh lettuce and special sauce",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "95",
            reorderedQuantity = "500+ orders",
            bestSeller = true,
            recommended = true,
        ),
        FoodItemDoubleF(
            id = 50,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_8,
                R.drawable.restaurant_image_pizzas_food_items_9
            ),
            title = "Crispy Chicken Burger",
            price = "79",
            originalPrice = "140",
            restaurantName = "Burger King",
            rating = "4.2",
            deliveryTime = "15-20 mins",
            distance = "1.3 km",
            discount = "35% OFF",
            discountAmount = "₹61 OFF",
            address = "Food Street, City Center",
            calories = "520 kcal",
            protein = "22g",
            isHighProtein = true,
            category = "burger",
            isWishlisted = false,
            description = "Crispy chicken patty with mayo and fresh veggies",
            quantity = "1",
            infoIcon = R.drawable.ic_non_veg_rest,
            highlyReordered = "85",
            reorderedQuantity = "569+ orders",
            bestSeller = true,
            recommended = true,
        ),
        FoodItemDoubleF(
            id = 51,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_9,
                R.drawable.restaurant_image_pizzas_food_items_10
            ),
            title = "Mexican Aloo Tikki Burger",
            price = "99",
            originalPrice = "160",
            restaurantName = "Burger King",
            rating = "4.3",
            deliveryTime = "18-22 mins",
            distance = "1.4 km",
            discount = "38% OFF",
            discountAmount = "₹61 OFF",
            address = "Food Plaza, Sector 5",
            calories = "480 kcal",
            protein = "12g",
            isHighProtein = false,
            category = "burger",
            isWishlisted = false,
            description = "Spicy aloo tikki with Mexican salsa and cheese",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "88",
            reorderedQuantity = "454+ orders",
            bestSeller = true,
            recommended = true,
        ),
        FoodItemDoubleF(
            id = 52,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_10,
                R.drawable.restaurant_image_pizzas_food_items_11
            ),
            title = "Veg American Cheese Supreme Burger",
            price = "129",
            originalPrice = "200",
            restaurantName = "Burger King",
            rating = "4.5",
            deliveryTime = "20-25 mins",
            distance = "1.5 km",
            discount = "35% OFF",
            discountAmount = "₹71 OFF",
            address = "Food Plaza, Sector 5",
            calories = "560 kcal",
            protein = "18g",
            isHighProtein = false,
            category = "burger",
            isWishlisted = false,
            description = "Double cheese, crispy veg patty, and special sauce",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "92",
            reorderedQuantity = "525+ orders",
            bestSeller = true,
            recommended = true,
        ),
        FoodItemDoubleF(
            id = 53,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_11,
                R.drawable.restaurant_image_pizzas_food_items_12
            ),
            title = "Royal Veg Burger",
            price = "198",
            originalPrice = "280",
            restaurantName = "Burger King",
            rating = "4.5",
            deliveryTime = "20-25 mins",
            distance = "1.5 km",
            discount = "29% OFF",
            discountAmount = "₹82 OFF",
            address = "Food Plaza, Sector 5",
            calories = "620 kcal",
            protein = "20g",
            isHighProtein = false,
            category = "burger",
            isWishlisted = false,
            description = "Premium veg burger with exotic veggies and royal sauce",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "90",
            reorderedQuantity = "400+ orders",
            bestSeller = true,
            recommended = true,
        ),
        FoodItemDoubleF(
            id = 54,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_12,
                R.drawable.restaurant_image_pizzas_food_items_7
            ),
            title = "Paneer Tikka Burger",
            price = "149",
            originalPrice = "220",
            restaurantName = "Burger King",
            rating = "4.6",
            deliveryTime = "18-22 mins",
            distance = "1.3 km",
            discount = "32% OFF",
            discountAmount = "₹71 OFF",
            address = "Food Street, City Center",
            calories = "510 kcal",
            protein = "19g",
            isHighProtein = true,
            category = "burger",
            isWishlisted = false,
            description = "Grilled paneer tikka burger with mint chutney",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "93",
            reorderedQuantity = "350+ orders",
            bestSeller = true,
            recommended = true,
        ),

        // Combo Burger category items (id 55 to 60)
        FoodItemDoubleF(
            id = 55,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_7,
                R.drawable.restaurant_image_pizzas_food_items_8
            ),
            title = "Crispy Veg Burger",
            price = "72",
            originalPrice = "120",
            restaurantName = "Burger King",
            rating = "5.0",
            deliveryTime = "15-20 mins",
            distance = "1.2 km",
            discount = "40% OFF",
            discountAmount = "₹48 OFF",
            address = "Food Street, City Center",
            calories = "450 kcal",
            protein = "15g",
            isHighProtein = false,
            category = "burger",
            isWishlisted = false,
            description = "Crispy veg patty with fresh lettuce and special sauce",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "95",
            reorderedQuantity = "500+ orders",
            bestSeller = true,
            combo = true,
        ),
        FoodItemDoubleF(
            id = 56,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_8,
                R.drawable.restaurant_image_pizzas_food_items_9
            ),
            title = "Crispy Chicken Burger",
            price = "79",
            originalPrice = "140",
            restaurantName = "Burger King",
            rating = "4.2",
            deliveryTime = "15-20 mins",
            distance = "1.3 km",
            discount = "35% OFF",
            discountAmount = "₹61 OFF",
            address = "Food Street, City Center",
            calories = "520 kcal",
            protein = "22g",
            isHighProtein = true,
            category = "burger",
            isWishlisted = false,
            description = "Crispy chicken patty with mayo and fresh veggies",
            quantity = "1",
            infoIcon = R.drawable.ic_non_veg_rest,
            highlyReordered = "85",
            reorderedQuantity = "569+ orders",
            bestSeller = true,
            combo = true,
        ),
        FoodItemDoubleF(
            id = 57,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_9,
                R.drawable.restaurant_image_pizzas_food_items_10
            ),
            title = "Mexican Aloo Tikki Burger",
            price = "99",
            originalPrice = "160",
            restaurantName = "Burger King",
            rating = "4.3",
            deliveryTime = "18-22 mins",
            distance = "1.4 km",
            discount = "38% OFF",
            discountAmount = "₹61 OFF",
            address = "Food Plaza, Sector 5",
            calories = "480 kcal",
            protein = "12g",
            isHighProtein = false,
            category = "burger",
            isWishlisted = false,
            description = "Spicy aloo tikki with Mexican salsa and cheese",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "88",
            reorderedQuantity = "454+ orders",
            bestSeller = true,
            combo = true,
        ),
        FoodItemDoubleF(
            id = 58,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_10,
                R.drawable.restaurant_image_pizzas_food_items_11
            ),
            title = "Veg American Cheese Supreme Burger",
            price = "129",
            originalPrice = "200",
            restaurantName = "Burger King",
            rating = "4.5",
            deliveryTime = "20-25 mins",
            distance = "1.5 km",
            discount = "35% OFF",
            discountAmount = "₹71 OFF",
            address = "Food Plaza, Sector 5",
            calories = "560 kcal",
            protein = "18g",
            isHighProtein = false,
            category = "burger",
            isWishlisted = false,
            description = "Double cheese, crispy veg patty, and special sauce",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "92",
            reorderedQuantity = "525+ orders",
            bestSeller = true,
            combo = true,
        ),
        FoodItemDoubleF(
            id = 59,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_11,
                R.drawable.restaurant_image_pizzas_food_items_12
            ),
            title = "Royal Veg Burger",
            price = "198",
            originalPrice = "280",
            restaurantName = "Burger King",
            rating = "4.5",
            deliveryTime = "20-25 mins",
            distance = "1.5 km",
            discount = "29% OFF",
            discountAmount = "₹82 OFF",
            address = "Food Plaza, Sector 5",
            calories = "620 kcal",
            protein = "20g",
            isHighProtein = false,
            category = "burger",
            isWishlisted = false,
            description = "Premium veg burger with exotic veggies and royal sauce",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "90",
            reorderedQuantity = "400+ orders",
            bestSeller = true,
            combo = true,
        ),
        FoodItemDoubleF(
            id = 60,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_12,
                R.drawable.restaurant_image_pizzas_food_items_7
            ),
            title = "Paneer Tikka Burger",
            price = "149",
            originalPrice = "220",
            restaurantName = "Burger King",
            rating = "4.6",
            deliveryTime = "18-22 mins",
            distance = "1.3 km",
            discount = "32% OFF",
            discountAmount = "₹71 OFF",
            address = "Food Street, City Center",
            calories = "510 kcal",
            protein = "19g",
            isHighProtein = true,
            category = "burger",
            isWishlisted = false,
            description = "Grilled paneer tikka burger with mint chutney",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "93",
            reorderedQuantity = "350+ orders",
            bestSeller = true,
            combo = true,
        ),

        // More Details Button Burger category items (id 61 to 66)
        FoodItemDoubleF(
            id = 61,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_7,
                R.drawable.restaurant_image_pizzas_food_items_8
            ),
            title = "Crispy Veg Burger + Crispy Chicken Burger",
            price = "72",
            originalPrice = "120",
            restaurantName = "Burger King",
            rating = "5.0",
            deliveryTime = "15-20 mins",
            distance = "1.2 km",
            discount = "40% OFF",
            discountAmount = "₹48 OFF",
            address = "Food Street, City Center",
            calories = "450 kcal",
            protein = "15g",
            isHighProtein = false,
            category = "burger",
            isWishlisted = false,
            description = "Crispy veg patty with fresh lettuce and special sauce",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "95",
            reorderedQuantity = "500+ orders",
            bestSeller = true,
            moredetailsbutton = true,
        ),
        FoodItemDoubleF(
            id = 62,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_8,
                R.drawable.restaurant_image_pizzas_food_items_9
            ),
            title = "Crispy Chicken Burger + Mexican Aloo Tikki Burger",
            price = "79",
            originalPrice = "140",
            restaurantName = "Burger King",
            rating = "4.2",
            deliveryTime = "15-20 mins",
            distance = "1.3 km",
            discount = "35% OFF",
            discountAmount = "₹61 OFF",
            address = "Food Street, City Center",
            calories = "520 kcal",
            protein = "22g",
            isHighProtein = true,
            category = "burger",
            isWishlisted = false,
            description = "Crispy chicken patty with mayo and fresh veggies",
            quantity = "1",
            infoIcon = R.drawable.ic_non_veg_rest,
            highlyReordered = "85",
            reorderedQuantity = "569+ orders",
            bestSeller = true,
            moredetailsbutton = true,
        ),
        FoodItemDoubleF(
            id = 63,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_9,
                R.drawable.restaurant_image_pizzas_food_items_10
            ),
            title = "Mexican Aloo Tikki Burger + Veg American Cheese Supreme Burger",
            price = "99",
            originalPrice = "160",
            restaurantName = "Burger King",
            rating = "4.3",
            deliveryTime = "18-22 mins",
            distance = "1.4 km",
            discount = "38% OFF",
            discountAmount = "₹61 OFF",
            address = "Food Plaza, Sector 5",
            calories = "480 kcal",
            protein = "12g",
            isHighProtein = false,
            category = "burger",
            isWishlisted = false,
            description = "Spicy aloo tikki with Mexican salsa and cheese",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "88",
            reorderedQuantity = "454+ orders",
            bestSeller = true,
            moredetailsbutton = true,
        ),
        FoodItemDoubleF(
            id = 64,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_10,
                R.drawable.restaurant_image_pizzas_food_items_11
            ),
            title = "Veg American Cheese Supreme Burger + Royal Veg Burger",
            price = "129",
            originalPrice = "200",
            restaurantName = "Burger King",
            rating = "4.5",
            deliveryTime = "20-25 mins",
            distance = "1.5 km",
            discount = "35% OFF",
            discountAmount = "₹71 OFF",
            address = "Food Plaza, Sector 5",
            calories = "560 kcal",
            protein = "18g",
            isHighProtein = false,
            category = "burger",
            isWishlisted = false,
            description = "Double cheese, crispy veg patty, and special sauce",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "92",
            reorderedQuantity = "525+ orders",
            bestSeller = true,
            moredetailsbutton = true,
        ),
        FoodItemDoubleF(
            id = 65,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_11,
                R.drawable.restaurant_image_pizzas_food_items_12
            ),
            title = "Royal Veg Burger + Paneer Tikka Burger",
            price = "198",
            originalPrice = "280",
            restaurantName = "Burger King",
            rating = "4.5",
            deliveryTime = "20-25 mins",
            distance = "1.5 km",
            discount = "29% OFF",
            discountAmount = "₹82 OFF",
            address = "Food Plaza, Sector 5",
            calories = "620 kcal",
            protein = "20g",
            isHighProtein = false,
            category = "burger",
            isWishlisted = false,
            description = "Premium veg burger with exotic veggies and royal sauce",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "90",
            reorderedQuantity = "400+ orders",
            bestSeller = true,
            moredetailsbutton = true,
        ),
        FoodItemDoubleF(
            id = 66,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_12,
                R.drawable.restaurant_image_pizzas_food_items_7
            ),
            title = "Paneer Tikka Burger + Crispy Veg Burger + Crispy Chicken Burger",
            price = "149",
            originalPrice = "220",
            restaurantName = "Burger King",
            rating = "4.6",
            deliveryTime = "18-22 mins",
            distance = "1.3 km",
            discount = "32% OFF",
            discountAmount = "₹71 OFF",
            address = "Food Street, City Center",
            calories = "510 kcal",
            protein = "19g",
            isHighProtein = true,
            category = "burger",
            isWishlisted = false,
            description = "Grilled paneer tikka burger with mint chutney",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "93",
            reorderedQuantity = "350+ orders",
            bestSeller = true,
            moredetailsbutton = true,
        ),

        // Salad Burger category items (id 67 to 72)
        FoodItemDoubleF(
            id = 67,
            imageRes = listOf(R.drawable.salad_veg_shammi),
            title = "Veg Shammi Salad",
            price = "289",
            originalPrice = "389",
            restaurantName = "FreshBowl",
            rating = "4.4",
            deliveryTime = "",
            distance = "",
            discount = "",
            discountAmount = "",
            address = "",
            calories = "361 kcal",
            protein = "13g",
            isHighProtein = true,
            category = "burger",
            isWishlisted = false,
            description = "Fresh cottage cheese marinated with spices, grilled to perfection on a bed of mixed greens",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "41",
            reorderedQuantity = "41 ratings",
            bestSeller = false,
            salad = true,
        ),
        FoodItemDoubleF(
            id = 68,
                imageRes = listOf(R.drawable.salad_smoked_chicken),
            title = "Smoked Chicken Strips Salad",
            price = "319",
            originalPrice = "489",
            restaurantName = "FreshBowl",
            rating = "4.2",
            deliveryTime = "",
            distance = "",
            discount = "",
            discountAmount = "",
            address = "",
            calories = "337 kcal",
            protein = "22g",
            isHighProtein = true,
            category = "burger",
            isWishlisted = false,
            description = "Tender smoked chicken strips with mixed greens, cherry tomatoes, and honey mustard dressing",
            quantity = "1",
            infoIcon = R.drawable.ic_non_veg_rest,
            highlyReordered = "0",
            reorderedQuantity = "",
            bestSeller = false,
            salad = true,
        ),
        FoodItemDoubleF(
            id = 69,
            imageRes = listOf(R.drawable.salad_paneer_tikka),
            title = "Paneer Tikka Salad",
            price = "289",
            originalPrice = "389",
            restaurantName = "FreshBowl",
            rating = "4.6",
            deliveryTime = "",
            distance = "",
            discount = "",
            discountAmount = "",
            address = "",
            calories = "380 kcal",
            protein = "18g",
            isHighProtein = true,
            category = "burger",
            isWishlisted = false,
            description = "Chargrilled paneer tikka on a bed of fresh veggies with mint chutney dressing",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "0",
            reorderedQuantity = "",
            bestSeller = true,
            salad = true,
        ),
        FoodItemDoubleF(
            id = 70,
            imageRes = listOf(R.drawable.salad_veggie_delite),
            title = "Veggie Delite Salad",
            price = "289",
            originalPrice = "389",
            restaurantName = "FreshBowl",
            rating = "4.0",
            deliveryTime = "",
            distance = "",
            discount = "",
            discountAmount = "",
            address = "",
            calories = "210 kcal",
            protein = "6g",
            isHighProtein = false,
            category = "burger",
            isWishlisted = false,
            description = "Fresh garden veggies including lettuce, cucumbers, bell peppers with light vinaigrette",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "0",
            reorderedQuantity = "",
            bestSeller = false,
            salad = true,
        ),
        FoodItemDoubleF(
            id = 71,
            imageRes = listOf(R.drawable.salad_corn_peas),
            title = "Corn & Peas Salad",
            price = "289",
            originalPrice = "389",
            restaurantName = "FreshBowl",
            rating = "4.8",
            deliveryTime = "",
            distance = "",
            discount = "",
            discountAmount = "",
            address = "",
            calories = "188 kcal",
            protein = "5g",
            isHighProtein = false,
            category = "burger",
            isWishlisted = false,
            description = "Sweet corn and green peas mixed with creamy yogurt dressing",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "28",
            reorderedQuantity = "28 ratings",
            bestSeller = false,
            salad = true,
        ),
        FoodItemDoubleF(
            id = 72,
            imageRes = listOf(R.drawable.salad_bmt),
            title = "B.M.T. Salad",
            price = "349",
            originalPrice = "449",
            restaurantName = "FreshBowl",
            rating = "5.0",
            deliveryTime = "",
            distance = "",
            discount = "",
            discountAmount = "",
            address = "",
            calories = "372 kcal",
            protein = "27g",
            isHighProtein = true,
            category = "burger",
            isWishlisted = false,
            description = "Hearty salad with multiple meats, fresh veggies, and signature sauce",
            quantity = "1",
            infoIcon = R.drawable.ic_non_veg_rest,
            highlyReordered = "7",
            reorderedQuantity = "7 ratings",
            bestSeller = false,
            salad = true,
        )

        // Big Bowl Category Food Items (IDs 13-18)
//        FoodItemDoubleF(
//            id = 13,
//            imageRes = listOf(R.drawable.restaurant_image_pizzas_food_items_13,
//                R.drawable.restaurant_image_pizzas_food_items_14),
//            title = "Aloo Tamatar with Rice Combo",
//            price = "149.50",
//            originalPrice = "299",
//            restaurantName = "Big Bowl",
//            rating = "4.3",
//            deliveryTime = "20-25 mins",
//            distance = "2.1 km",
//            discount = "50% OFF",
//            discountAmount = "₹149.50 OFF",
//            address = "Big Bowl Kitchen, Downtown",
//            calories = "620 kcal",
//            protein = "11g",
//            isHighProtein = false,
//            category = "bigbowl",
//            isWishlisted = false,
//            description = "Classic aloo tamatar curry served with 800ml steamed rice. A comforting North Indian meal.",
//            quantity = "800 ml",
//            infoIcon = R.drawable.ic_veg_rest,
//            highlyReordered = "78",
//            reorderedQuantity = "220+ orders",
//            bestSeller = true,
//        ),
//        FoodItemDoubleF(
//            id = 14,
//            imageRes = listOf(R.drawable.restaurant_image_pizzas_food_items_14,
//                R.drawable.restaurant_image_pizzas_food_items_15),
//            title = "Dal Makhani + Rice Combo Pack",
//            price = "199",
//            originalPrice = "299",
//            restaurantName = "Big Bowl",
//            rating = "4.5",
//            deliveryTime = "22-27 mins",
//            distance = "2.3 km",
//            discount = "33% OFF",
//            discountAmount = "₹100 OFF",
//            address = "Big Bowl Kitchen, Downtown",
//            calories = "710 kcal",
//            protein = "18g",
//            isHighProtein = true,
//            category = "bigbowl",
//            isWishlisted = false,
//            description = "500ml creamy Dal Makhani + 500ml steamed rice. Not eligible for coupons.",
//            quantity = "1000 ml (500+500)",
//            infoIcon = R.drawable.ic_veg_rest,
//            highlyReordered = "94",
//            reorderedQuantity = "500+ orders",
//            bestSeller = true,
//        ),
//        FoodItemDoubleF(
//            id = 15,
//            imageRes = listOf(R.drawable.restaurant_image_pizzas_food_items_15,
//                R.drawable.restaurant_image_pizzas_food_items_16),
//            title = "Rajma with Rice",
//            price = "199",
//            originalPrice = "249",
//            restaurantName = "Big Bowl",
//            rating = "4.4",
//            deliveryTime = "20-25 mins",
//            distance = "1.9 km",
//            discount = "20% OFF",
//            discountAmount = "₹50 OFF",
//            address = "Big Bowl Kitchen, Downtown",
//            calories = "590 kcal",
//            protein = "16g",
//            isHighProtein = true,
//            category = "bigbowl",
//            isWishlisted = false,
//            description = "Rajma is a delicious dish of Punjabi cuisine and is popular all over India. This spicy red kidney bean curry pairs perfectly with rice.",
//            quantity = "800 ml",
//            infoIcon = R.drawable.ic_veg_rest,
//            highlyReordered = "88",
//            reorderedQuantity = "430+ orders",
//            bestSeller = false,
//        ),
//        FoodItemDoubleF(
//            id = 16,
//            imageRes = listOf(R.drawable.restaurant_image_pizzas_food_items_16,
//                R.drawable.restaurant_image_pizzas_food_items_17),
//            title = "4 Triangle Paratha with Matar Paneer",
//            price = "220",
//            originalPrice = "280",
//            restaurantName = "Big Bowl",
//            rating = "4.7",
//            deliveryTime = "18-23 mins",
//            distance = "1.7 km",
//            discount = "21% OFF",
//            discountAmount = "₹60 OFF",
//            address = "Big Bowl Kitchen, Downtown",
//            calories = "890 kcal",
//            protein = "22g",
//            isHighProtein = true,
//            category = "bigbowl",
//            isWishlisted = false,
//            description = "Triangle paratha 3 layers and soft bhashahi paneer cut in square type onion tomato gravy.",
//            quantity = "4 pcs + 300 ml curry",
//            infoIcon = R.drawable.ic_veg_rest,
//            highlyReordered = "96",
//            reorderedQuantity = "610+ orders",
//            bestSeller = true,
//        ),
//        FoodItemDoubleF(
//            id = 17,
//            imageRes = listOf(R.drawable.restaurant_image_pizzas_food_items_17,
//                R.drawable.restaurant_image_pizzas_food_items_18),
//            title = "Deluxe Thali",
//            price = "249",
//            originalPrice = "349",
//            restaurantName = "Big Bowl",
//            rating = "4.8",
//            deliveryTime = "20-25 mins",
//            distance = "2.0 km",
//            discount = "28% OFF",
//            discountAmount = "₹100 OFF",
//            address = "Big Bowl Kitchen, Downtown",
//            calories = "1050 kcal",
//            protein = "28g",
//            isHighProtein = true,
//            category = "bigbowl",
//            isWishlisted = false,
//            description = "4 Chapati + Matar Paneer / Dal Makhani + Mix Veg + Rice + Raita + Salad. Highly reordered.",
//            quantity = "Full Thali",
//            infoIcon = R.drawable.ic_veg_rest,
//            highlyReordered = "98",
//            reorderedQuantity = "1200+ orders",
//            bestSeller = true,
//        ),
//        FoodItemDoubleF(
//            id = 18,
//            imageRes = listOf(R.drawable.restaurant_image_pizzas_food_items_18,
//                R.drawable.restaurant_image_pizzas_food_items_13),
//            title = "Matar Paneer with 2 Butter Naan",
//            price = "229",
//            originalPrice = "299",
//            restaurantName = "Big Bowl",
//            rating = "4.6",
//            deliveryTime = "18-22 mins",
//            distance = "1.5 km",
//            discount = "23% OFF",
//            discountAmount = "₹70 OFF",
//            address = "Big Bowl Kitchen, Downtown",
//            calories = "780 kcal",
//            protein = "20g",
//            isHighProtein = true,
//            category = "bigbowl",
//            isWishlisted = false,
//            description = "Creamy matar paneer curry served with 2 soft butter naan. A customer favorite.",
//            quantity = "300 ml curry + 2 naan",
//            infoIcon = R.drawable.ic_veg_rest,
//            highlyReordered = "91",
//            reorderedQuantity = "530+ orders",
//            bestSeller = false,
//        ),
    )

    // Helper function to get items by category
    fun getItemsByCategory(category: String): List<FoodItemDoubleF> {
        return allFoodItems.filter { it.category.equals(category, ignoreCase = true) }
    }

    // Helper function to get bestseller items
    fun getBestsellerItems(): List<FoodItemDoubleF> {
        return allFoodItems.filter { it.bestSeller == true }
    }

    // Helper function to get item by id
    fun getItemById(id: Int): FoodItemDoubleF? {
        return allFoodItems.find { it.id == id }
    }

    // Helper function to get wishlisted items
    fun getWishlistedItems(): List<FoodItemDoubleF> {
        return allFoodItems.filter { it.isWishlisted == true }
    }
}