package com.example.qrakon.components.restaurants

import com.example.qrakon.R
import com.example.qrakon.components.restaurants.FoodItemDoubleF

object RestaurantData {

    val allFoodItems = listOf(
        FoodItemDoubleF(
            id = 1,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_1,
                R.drawable.restaurant_image_pizzas_food_items_2
            ),
            title = "Chicken Pizza",
            price = "275",
            originalPrice = "375",
            restaurantName = "Burger Hub",
            rating = "4.3",
            deliveryTime = "20-25 mins",
            distance = "1.8 km",
            discount = "10% OFF",
            discountAmount = "₹25 OFF",
            address = "Food Street, City Center",
            calories = "450 kcal",
            protein = "22g",
            isHighProtein = true,
            category = "pizza",
            isWishlisted = false,
            description = "Juicy chicken burger with fresh lettuce, tomato and crispy fries",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "70",
            reorderedQuantity = "150+ orders",
            bestSeller = true,
        ),
        FoodItemDoubleF(
            id = 2,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_2,
                R.drawable.restaurant_image_pizzas_food_items_3
            ),
            title = "Chilli Garlic Pizza",
            price = "363",
            originalPrice = "563",
            restaurantName = "Momo Express",
            rating = "4.5",
            deliveryTime = "25-30 mins",
            distance = "2.2 km",
            discount = "15% OFF",
            discountAmount = "₹40 OFF",
            address = "Downtown Food Plaza",
            calories = "380 kcal",
            protein = "14g",
            isHighProtein = false,
            category = "pizza",
            isWishlisted = true,
            description = "Spicy chilli garlic momos tossed with flavorful sauces and herbs",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "65",
            reorderedQuantity = "200+ orders",
            bestSeller = false,
        ),
        FoodItemDoubleF(
            id = 3,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_3,
                R.drawable.restaurant_image_pizzas_food_items_4
            ),
            title = "Ultimate Cheese Pizza",
            price = "399",
            originalPrice = "499",
            restaurantName = "Pizza Heaven",
            rating = "4.3",
            deliveryTime = "25-30 mins",
            distance = "2.5 km",
            discount = "",
            discountAmount = "",
            address = "Food Court, Mall Road",
            calories = "780 kcal",
            protein = "24g",
            isHighProtein = false,
            category = "pizza",
            isWishlisted = false,
            description = "Classic margherita with extra cheese and basil",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "",
            reorderedQuantity = "",
            bestSeller = false,
        ),
        FoodItemDoubleF(
            id = 4,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_4,
                R.drawable.restaurant_image_pizzas_food_items_5
            ),
            title = "Corn Pizza",
            price = "139",
            originalPrice = "239",
            restaurantName = "Pizza Corner",
            rating = "3.8",
            deliveryTime = "20-25 mins",
            distance = "1.5 km",
            discount = "",
            discountAmount = "",
            address = "Street Food Market",
            calories = "620 kcal",
            protein = "16g",
            isHighProtein = false,
            category = "pizza",
            isWishlisted = false,
            description = "Sweet corn pizza with creamy sauce",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "Highly reordered",
            reorderedQuantity = "",
            bestSeller = true,
        ),
        FoodItemDoubleF(
            id = 5,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_5,
                R.drawable.restaurant_image_pizzas_food_items_6
            ),
            title = "Ultimate Flotzz Pizza",
            price = "399",
            originalPrice = "499",
            restaurantName = "Flotzz Pizza",
            rating = "4.2",
            deliveryTime = "30-35 mins",
            distance = "3.0 km",
            discount = "",
            discountAmount = "",
            address = "Food Plaza, Sector 5",
            calories = "850 kcal",
            protein = "32g",
            isHighProtein = true,
            category = "pizza",
            isWishlisted = false,
            description = "Loaded with cheese and toppings",
            quantity = "1",
            infoIcon = R.drawable.ic_non_veg_rest,
            highlyReordered = "",
            reorderedQuantity = "500+ orders",
            bestSeller = true,
        ),
        FoodItemDoubleF(
            id = 6,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_6,
                R.drawable.restaurant_image_pizzas_food_items_1
            ),
            title = "Tandoori Chicken Pizza",
            price = "399",
            originalPrice = "499",
            restaurantName = "Flotzz Pizza",
            rating = "4.5",
            deliveryTime = "30-35 mins",
            distance = "3.0 km",
            discount = "",
            discountAmount = "",
            address = "Food Plaza, Sector 5",
            calories = "890 kcal",
            protein = "38g",
            isHighProtein = true,
            category = "pizza",
            isWishlisted = true,
            description = "Tandoori chicken with spicy sauce",
            quantity = "1",
            infoIcon = R.drawable.ic_non_veg_rest,
            highlyReordered = "",
            reorderedQuantity = "500+ orders",
            bestSeller = false,
        ),
        // Burger category items (id 7 to 12)
        FoodItemDoubleF(
            id = 7,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_7,
                R.drawable.restaurant_image_pizzas_food_items_8
            ),
            title = "Crispy Veg Burger",
            price = "72",
            originalPrice = "120",
            restaurantName = "Burger King",
            rating = "5.0",
            deliveryTime = "15-20 mins",
            distance = "1.2 km",
            discount = "40% OFF",
            discountAmount = "₹48 OFF",
            address = "Food Street, City Center",
            calories = "450 kcal",
            protein = "15g",
            isHighProtein = false,
            category = "burger",
            isWishlisted = false,
            description = "Crispy veg patty with fresh lettuce and special sauce",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "95",
            reorderedQuantity = "500+ orders",
            bestSeller = true,
        ),
        FoodItemDoubleF(
            id = 8,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_8,
                R.drawable.restaurant_image_pizzas_food_items_9
            ),
            title = "Crispy Chicken Burger",
            price = "79",
            originalPrice = "140",
            restaurantName = "Burger King",
            rating = "4.2",
            deliveryTime = "15-20 mins",
            distance = "1.3 km",
            discount = "35% OFF",
            discountAmount = "₹61 OFF",
            address = "Food Street, City Center",
            calories = "520 kcal",
            protein = "22g",
            isHighProtein = true,
            category = "burger",
            isWishlisted = false,
            description = "Crispy chicken patty with mayo and fresh veggies",
            quantity = "1",
            infoIcon = R.drawable.ic_non_veg_rest,
            highlyReordered = "85",
            reorderedQuantity = "569+ orders",
            bestSeller = true,
        ),
        FoodItemDoubleF(
            id = 9,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_9,
                R.drawable.restaurant_image_pizzas_food_items_10
            ),
            title = "Mexican Aloo Tikki Burger",
            price = "99",
            originalPrice = "160",
            restaurantName = "Burger King",
            rating = "4.3",
            deliveryTime = "18-22 mins",
            distance = "1.4 km",
            discount = "38% OFF",
            discountAmount = "₹61 OFF",
            address = "Food Plaza, Sector 5",
            calories = "480 kcal",
            protein = "12g",
            isHighProtein = false,
            category = "burger",
            isWishlisted = false,
            description = "Spicy aloo tikki with Mexican salsa and cheese",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "88",
            reorderedQuantity = "454+ orders",
            bestSeller = true,
        ),
        FoodItemDoubleF(
            id = 10,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_10,
                R.drawable.restaurant_image_pizzas_food_items_11
            ),
            title = "Veg American Cheese Supreme Burger",
            price = "129",
            originalPrice = "200",
            restaurantName = "Burger King",
            rating = "4.5",
            deliveryTime = "20-25 mins",
            distance = "1.5 km",
            discount = "35% OFF",
            discountAmount = "₹71 OFF",
            address = "Food Plaza, Sector 5",
            calories = "560 kcal",
            protein = "18g",
            isHighProtein = false,
            category = "burger",
            isWishlisted = false,
            description = "Double cheese, crispy veg patty, and special sauce",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "92",
            reorderedQuantity = "525+ orders",
            bestSeller = true,
        ),
        FoodItemDoubleF(
            id = 11,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_11,
                R.drawable.restaurant_image_pizzas_food_items_12
            ),
            title = "Royal Veg Burger",
            price = "198",
            originalPrice = "280",
            restaurantName = "Burger King",
            rating = "4.5",
            deliveryTime = "20-25 mins",
            distance = "1.5 km",
            discount = "29% OFF",
            discountAmount = "₹82 OFF",
            address = "Food Plaza, Sector 5",
            calories = "620 kcal",
            protein = "20g",
            isHighProtein = false,
            category = "burger",
            isWishlisted = false,
            description = "Premium veg burger with exotic veggies and royal sauce",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "90",
            reorderedQuantity = "400+ orders",
            bestSeller = true,
        ),
        FoodItemDoubleF(
            id = 12,
            imageRes = listOf(
                R.drawable.restaurant_image_pizzas_food_items_12,
                R.drawable.restaurant_image_pizzas_food_items_7
            ),
            title = "Paneer Tikka Burger",
            price = "149",
            originalPrice = "220",
            restaurantName = "Burger King",
            rating = "4.6",
            deliveryTime = "18-22 mins",
            distance = "1.3 km",
            discount = "32% OFF",
            discountAmount = "₹71 OFF",
            address = "Food Street, City Center",
            calories = "510 kcal",
            protein = "19g",
            isHighProtein = true,
            category = "burger",
            isWishlisted = false,
            description = "Grilled paneer tikka burger with mint chutney",
            quantity = "1",
            infoIcon = R.drawable.ic_veg_rest,
            highlyReordered = "93",
            reorderedQuantity = "350+ orders",
            bestSeller = true,
        ),
    )

    // Helper function to get items by category
    fun getItemsByCategory(category: String): List<FoodItemDoubleF> {
        return allFoodItems.filter { it.category.equals(category, ignoreCase = true) }
    }

    // Helper function to get bestseller items
    fun getBestsellerItems(): List<FoodItemDoubleF> {
        return allFoodItems.filter { it.bestSeller == true }
    }

    // Helper function to get item by id
    fun getItemById(id: Int): FoodItemDoubleF? {
        return allFoodItems.find { it.id == id }
    }

    // Helper function to get wishlisted items
    fun getWishlistedItems(): List<FoodItemDoubleF> {
        return allFoodItems.filter { it.isWishlisted == true }
    }
}